// Code generated by command: go run decoderAVX2_amd64_asm.go -out ../../decoderAVX2_amd64.s -pkg decoder. DO NOT EDIT.

#include "textflag.h"

// func decodeSIMDAVX2(src []byte, dest *[]byte, escFirst *byte, nextMask *uint16)
TEXT ·decodeSIMDAVX2(SB), NOSPLIT, $0-48
	MOVQ src_base+0(FP), AX
	MOVQ src_len+8(FP), CX
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-42, AL
	MOVB $-106, AL
	RET
